### ISSUE TITLE
Can we delete this repo?

### ISSUE THREAD

**Issue by gr2m** [hoodiehq-archive/legacy-hoodie-vagrant#3]

**Comment by ptrwllrt** [comment]
To be honest. I didn't manage to cover any of the issues in the last months. Also do not see it happening. It's rather anyone taking over or it should go. :<

**Comment by varjmes** [comment]
I'd say get rid of it and if the problem arises (we want a vagrant project with hoodie in it) then we can start again? It's been 3 years.

Thanks for your work and input @cainvommars 💃

**Comment by gr2m** [comment]
I’ve renamed the repo to `legacy-hoodie-vagrant` and set description to `⛔ not up-to-date`

**Comment by varjmes** [comment]
LGTM! I'll close this then :)
